Repository Nine-Byte-Warriors/roche-engine, pull requests merged in 2023-01, with the labels that each got.

#36 Entity component system
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Objects/Camera2D.cpp
  Studio Sim/Objects/Camera2D.h
  Studio Sim/Objects/Enemy.cpp
  Studio Sim/Objects/Enemy.h
  Studio Sim/Objects/GameObject.h
  Studio Sim/Objects/Player.cpp
  Studio Sim/Objects/Player.h
  Studio Sim/Objects/Sprite.cpp
  Studio Sim/Objects/Sprite.h
  Studio Sim/Resources/Shaders/shader2D_VS.hlsl
  Studio Sim/Resources/Textures/Onion.png
  Studio Sim/Resources/Textures/bean_ss.png
  Studio Sim/Resources/Textures/carrot_ss.png
  Studio Sim/Resources/Textures/cauliflower_ss.png
  Studio Sim/Resources/Textures/mesh.png
  Studio Sim/Resources/Textures/onion_ss.png
  Studio Sim/Resources/Textures/tomato_ss.png
  Studio Sim/Resources/Textures/wood.png
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/TileMap/TileMap.cpp
  Studio Sim/TileMap/TileMap.h
  Studio Sim/TileMap/TileMapEditor.cpp
  Studio Sim/TileMap/TileMapEditor.h
  Studio Sim/Utility/Vector2f.h
  Studio Sim/Utility/structures.h
Labels: engine

#39 Ai logic
  Studio Sim/AILogic/AIFlee.cpp
  Studio Sim/AILogic/AIFlee.h
  Studio Sim/AILogic/AIIdle.cpp
  Studio Sim/AILogic/AIIdle.h
  Studio Sim/AILogic/AIPatrol.cpp
  Studio Sim/AILogic/AIPatrol.h
  Studio Sim/AILogic/AISeek.cpp
  Studio Sim/AILogic/AISeek.h
  Studio Sim/AILogic/AIState.h
  Studio Sim/AILogic/AIStateMachine.cpp
  Studio Sim/AILogic/AIStateMachine.h
  Studio Sim/Events/Event.h
  Studio Sim/Graphics/ImGuiManager.cpp
  Studio Sim/Graphics/ImGuiManager.h
  Studio Sim/Input/Input.cpp
  Studio Sim/Input/Input.h
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Objects/Agent.cpp
  Studio Sim/Objects/Agent.h
  Studio Sim/Objects/Cube.cpp
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Utility/Vector2f.h
  Studio Sim/imgui.ini
Labels: engine

#37 Transform component
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Objects/Camera2D.cpp
  Studio Sim/Objects/Camera2D.h
  Studio Sim/Objects/Enemy.cpp
  Studio Sim/Objects/Enemy.h
  Studio Sim/Objects/GameObject.cpp
  Studio Sim/Objects/Player.cpp
  Studio Sim/Objects/Player.h
  Studio Sim/Objects/Transform.cpp
  Studio Sim/Objects/Transform.h
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
Labels: engine

#38 Adding in Json loading for tilemap
  Studio Sim/TileMap.json
  Studio Sim/TileMap/TileMap.cpp
  Studio Sim/TileMap/TileMap.h
  Studio Sim/TileMap/TileMapEditor.cpp
  Studio Sim/TileMap/TileMapEditor.h
Labels: engine

#40 Sprite animations
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Objects/Enemy.cpp
  Studio Sim/Objects/Player.cpp
  Studio Sim/Objects/Sprite.cpp
  Studio Sim/Objects/Sprite.h
  Studio Sim/TileMap/TileMapEditor.cpp
Labels: engine

#41 Draws the tile map to the render
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Resources/Textures/Base_tiles.png
  Studio Sim/Resources/Textures/Base_tiles512.png
  Studio Sim/Resources/Textures/dirt.png
  Studio Sim/Resources/Textures/empty.png
  Studio Sim/Resources/Textures/empty2.png
  Studio Sim/Resources/Textures/grass.png
  Studio Sim/Resources/Textures/lilly.png
  Studio Sim/Resources/Textures/wall.png
  Studio Sim/Resources/TileMaps/TileMap.json
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/TileMap/TileMap.cpp
  Studio Sim/TileMap/TileMap.h
  Studio Sim/TileMap/TileMapDraw.cpp
  Studio Sim/TileMap/TileMapDraw.h
  Studio Sim/TileMap/TileMapEditor.cpp
  Studio Sim/TileMap/TileMapEditor.h
  Studio Sim/imgui.ini
Labels: engine

#42 Basic Collision Detection
  Studio Sim/Collisions/Collider.h
  Studio Sim/Collisions/Collision.cpp
  Studio Sim/Collisions/Collision.h
  Studio Sim/Collisions/Rect2f.h
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/Utility/Vector2f.h
Labels: engine

#47 Improved window resizing
  Studio Sim/Application.h
  Studio Sim/Graphics/Graphics.cpp
  Studio Sim/Graphics/Graphics.h
  Studio Sim/Graphics/ImGuiManager.cpp
  Studio Sim/Graphics/ImGuiManager.h
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Levels/LevelContainer.h
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/Systems/PostProcessing.cpp
  Studio Sim/Systems/PostProcessing.h
  Studio Sim/Window/WindowContainer.cpp
  Studio Sim/imgui.ini
Labels: engine, enhancement

#48 Projectiles, Manager and Pool
  Studio Sim/AILogic/AIFlee.cpp
  Studio Sim/AILogic/AISeek.cpp
  Studio Sim/Events/Event.h
  Studio Sim/Input/Input.cpp
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Objects/Enemy.cpp
  Studio Sim/Objects/Enemy.h
  Studio Sim/Objects/Player.cpp
  Studio Sim/Objects/Player.h
  Studio Sim/Objects/Projectile.cpp
  Studio Sim/Objects/Projectile.h
  Studio Sim/Resources/Textures/Base_Projectile.png
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/Systems/Agent.cpp
  Studio Sim/Systems/ProjectileManager.cpp
  Studio Sim/Systems/ProjectileManager.h
  Studio Sim/Systems/Sprite.cpp
  Studio Sim/Systems/Sprite.h
  Studio Sim/Utility/Vector2f.h
  Studio Sim/Utility/structures.h
  Studio Sim/Window/WindowContainer.cpp
  Studio Sim/imgui.ini
Labels: engine

#49 TileMap foreground and background added
  External/imgui/imgui_widgets.cpp
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Resources/Textures/100transparent.png
  Studio Sim/Resources/TileMaps/TileMap.json
  Studio Sim/TileMap/TileMap.cpp
  Studio Sim/TileMap/TileMap.h
  Studio Sim/TileMap/TileMapEditor.cpp
  Studio Sim/TileMap/TileMapEditor.h
Labels: engine

#50 Tile Maps now save as json
  Studio Sim/Resources/TileMaps/6x6.txt
  Studio Sim/Resources/TileMaps/6x6_2.txt
  Studio Sim/Resources/TileMaps/6x6_3.txt
  Studio Sim/Resources/TileMaps/testjson.json
  Studio Sim/TileMap/TileMapEditor.cpp
  Studio Sim/TileMap/TileMapEditor.h
Labels: engine

#51 Basic UI widgets added
  Studio Sim/Application.cpp
  Studio Sim/Application.h
  Studio Sim/Collisions/Rect2f.h
  Studio Sim/Events/Event.h
  Studio Sim/Graphics/Graphics.cpp
  Studio Sim/Graphics/Graphics.h
  Studio Sim/Input/Input.cpp
  Studio Sim/Input/Input.h
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Levels/LevelContainer.h
  Studio Sim/Resources/Textures/github_logo.png
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/UI/UIElement.cpp
  Studio Sim/UI/UIElement.h
  Studio Sim/UI/UIManager.cpp
  Studio Sim/UI/UIManager.h
  Studio Sim/UI/UIScreen.cpp
  Studio Sim/UI/UIScreen.h
  Studio Sim/UI/WidgetIncludes.h
  Studio Sim/UI/Widgets/Button_Widget.cpp
  Studio Sim/UI/Widgets/Button_Widget.h
  Studio Sim/UI/Widgets/ColourBlock_Widget.cpp
  Studio Sim/UI/Widgets/ColourBlock_Widget.h
  Studio Sim/UI/Widgets/DataSlider_Widget.cpp
  Studio Sim/UI/Widgets/DataSlider_Widget.h
  Studio Sim/UI/Widgets/DropDown_Widget.cpp
  Studio Sim/UI/Widgets/DropDown_Widget.h
  Studio Sim/UI/Widgets/EnergyBar_Widget.cpp
  Studio Sim/UI/Widgets/EnergyBar_Widget.h
  Studio Sim/UI/Widgets/Image_Widget.cpp
  Studio Sim/UI/Widgets/Image_Widget.h
  Studio Sim/UI/Widgets/Input_Widget.cpp
  Studio Sim/UI/Widgets/Input_Widget.h
  Studio Sim/UI/Widgets/PageSlider_Widget.cpp
  Studio Sim/UI/Widgets/PageSlider_Widget.h
  Studio Sim/UI/Widgets/Widget.h
  Studio Sim/Window/RenderWindow.cpp
  Studio Sim/Window/WindowContainer.cpp
Labels: engine

#52 Data slider and energy bar
  Studio Sim/Application.cpp
  Studio Sim/Events/Event.h
  Studio Sim/Input/Input.cpp
  Studio Sim/Input/Input.h
  Studio Sim/Objects/Player.h
  Studio Sim/Resources/Tutorial01.rc
  Studio Sim/Resources/directx.ico
  Studio Sim/Resources/farm.ico
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/UI/UIScreen.cpp
  Studio Sim/UI/UIScreen.h
  Studio Sim/UI/WidgetIncludes.h
  Studio Sim/UI/Widgets/Button_Widget.cpp
  Studio Sim/UI/Widgets/Button_Widget.h
  Studio Sim/UI/Widgets/DataSlider_Widget.cpp
  Studio Sim/UI/Widgets/DataSlider_Widget.h
  Studio Sim/UI/Widgets/EnergyBar_Widget.cpp
  Studio Sim/UI/Widgets/EnergyBar_Widget.h
  Studio Sim/Utility/Texture.cpp
Labels: engine

#53 Collision System
  Studio Sim/Collisions/Collider.h
  Studio Sim/Collisions/Collision.cpp
  Studio Sim/Collisions/Collision.h
  Studio Sim/Collisions/CollisionHandler.cpp
  Studio Sim/Collisions/CollisionHandler.h
Labels: engine

#60 Json loads per struct
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/Utility/JsonLoading.h
  Studio Sim/cpp.hint
Labels: engine

#61 Implemented Collision System and Resolution
  Studio Sim/Collisions/CollisionHandler.cpp
  Studio Sim/Collisions/CollisionHandler.h
  Studio Sim/Components/Agent.cpp
  Studio Sim/Components/Agent.h
  Studio Sim/Components/Collider.cpp
  Studio Sim/Components/Collider.h
  Studio Sim/Components/Physics.cpp
  Studio Sim/Components/Physics.h
  Studio Sim/Components/ProjectileManager.cpp
  Studio Sim/Components/ProjectileManager.h
  Studio Sim/Components/Sprite.cpp
  Studio Sim/Components/Sprite.h
  Studio Sim/Components/Transform.cpp
  Studio Sim/Components/Transform.h
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Objects/Enemy.cpp
  Studio Sim/Objects/Enemy.h
  Studio Sim/Objects/Player.cpp
  Studio Sim/Objects/Player.h
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/Utility/Errors/COMException.h
  Studio Sim/Utility/Errors/ErrorLogger.cpp
  Studio Sim/Utility/Errors/ErrorLogger.h
  Studio Sim/Utility/Helper/FileLoading.cpp
  Studio Sim/Utility/Helper/FileLoading.h
  Studio Sim/Utility/Helper/JsonLoading.h
  Studio Sim/Utility/Helper/StringHelper.cpp
  Studio Sim/Utility/Helper/StringHelper.h
  Studio Sim/Utility/Helper/TextRenderer.cpp
  Studio Sim/Utility/Helper/TextRenderer.h
  Studio Sim/Utility/Helper/ThreadManager.cpp
  Studio Sim/Utility/Helper/ThreadManager.h
  Studio Sim/Utility/Helper/Timer.cpp
  Studio Sim/Utility/Helper/Timer.h
  Studio Sim/Utility/Helper/Vector2f.h
  Studio Sim/Utility/Rendering/Colour.cpp
  Studio Sim/Utility/Rendering/Colour.h
  Studio Sim/Utility/Rendering/DDSTextureLoader.cpp
  Studio Sim/Utility/Rendering/DDSTextureLoader.h
  Studio Sim/Utility/Rendering/Shader_Data.h
  Studio Sim/Utility/Rendering/Texture.cpp
  Studio Sim/Utility/Rendering/Texture.h
  Studio Sim/imgui.ini
Labels: engine

#65 Json loading update & tilemap to use new json
  Studio Sim/Resources/TileMaps/TileMap.json
  Studio Sim/TileMap/TileMap.cpp
  Studio Sim/TileMap/TileMap.h
  Studio Sim/TileMap/TileMapEditor.cpp
  Studio Sim/Utility/Helper/JsonLoading.h
Labels: engine

#96 Feat/entity
  Studio Sim/Audio/AudioEditor.cpp
  Studio Sim/Audio/AudioEditor.h
  Studio Sim/Components/Entity.cpp
  Studio Sim/Components/Entity.h
  Studio Sim/Components/EntityController.cpp
  Studio Sim/Components/EntityController.h
  Studio Sim/Components/EntityEditor.cpp
  Studio Sim/Components/EntityEditor.h
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Resources/Entity/Entity.json
  Studio Sim/Resources/TileMaps/tesjson2.json
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
Labels: engine

#102 Fixed issue with unwanted UI clicks
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/UI/UIScreen.cpp
  Studio Sim/UI/UIScreen.h
  Studio Sim/UI/Widgets/Button_Widget.cpp
  Studio Sim/UI/Widgets/Button_Widget.h
  Studio Sim/UI/Widgets/DataSlider_Widget.cpp
  Studio Sim/UI/Widgets/DataSlider_Widget.h
  Studio Sim/UI/Widgets/DropDown_Widget.cpp
  Studio Sim/UI/Widgets/DropDown_Widget.h
  Studio Sim/UI/Widgets/Input_Widget.cpp
  Studio Sim/UI/Widgets/PageSlider_Widget.cpp
  Studio Sim/UI/Widgets/PageSlider_Widget.h
  Studio Sim/UI/Widgets/Widget.h
  Studio Sim/imgui.ini
Labels: bug, engine

#103 Fixed page slider positioning
  Studio Sim/UI/Widgets/PageSlider_Widget.cpp
Labels: engine, enhancement

#108 Projectile editor
  Studio Sim/Audio/AudioEditor.cpp
  Studio Sim/Audio/AudioEditor.h
  Studio Sim/Components/ProjectileEditor.cpp
  Studio Sim/Components/ProjectileEditor.h
  Studio Sim/Components/ProjectileManager.cpp
  Studio Sim/Components/ProjectileManager.h
  Studio Sim/Components/Sprite.cpp
  Studio Sim/Components/Sprite.h
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Objects/Player.cpp
  Studio Sim/Objects/Player.h
  Studio Sim/Objects/Projectile.cpp
  Studio Sim/Objects/Projectile.h
  Studio Sim/Resources/Patterns/DefaultManagerPattern.ptn
  Studio Sim/Resources/Patterns/DefaultProjectile2.ptn
  Studio Sim/Resources/Patterns/SlowCircle.ptn
  Studio Sim/Resources/Patterns/SlowWiggle.ptn
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/TileMap/TileMapEditor.cpp
  Studio Sim/TileMap/TileMapEditor.h
  Studio Sim/Utility/Helper/Vector2f.h
  Studio Sim/Utility/JsonLoading.h
  Studio Sim/Utility/ProjectileData.h
  Studio Sim/imgui.ini
Labels: engine

#111 UI editor
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Resources/UI/Main Menu.json
  Studio Sim/Resources/UI/Screens/Credits.json
  Studio Sim/Resources/UI/Screens/HUD.json
  Studio Sim/Resources/UI/Screens/Menu.json
  Studio Sim/Resources/UI/Screens/Pause.json
  Studio Sim/Resources/UI/Screens/Settings.json
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/UI/UIEditor.cpp
  Studio Sim/UI/UIEditor.h
  Studio Sim/UI/UIManager.cpp
  Studio Sim/UI/UIManager.h
  Studio Sim/UI/UIScreen.cpp
  Studio Sim/UI/UIScreen.h
  Studio Sim/UI/Widgets/Button_Widget.cpp
  Studio Sim/UI/Widgets/Button_Widget.h
  Studio Sim/UI/Widgets/ColourBlock_Widget.cpp
  Studio Sim/UI/Widgets/ColourBlock_Widget.h
  Studio Sim/UI/Widgets/DataSlider_Widget.cpp
  Studio Sim/UI/Widgets/DataSlider_Widget.h
  Studio Sim/UI/Widgets/DropDown_Widget.cpp
  Studio Sim/UI/Widgets/DropDown_Widget.h
  Studio Sim/UI/Widgets/EnergyBar_Widget.cpp
  Studio Sim/UI/Widgets/EnergyBar_Widget.h
  Studio Sim/UI/Widgets/Image_Widget.cpp
  Studio Sim/UI/Widgets/Image_Widget.h
  Studio Sim/UI/Widgets/Input_Widget.cpp
  Studio Sim/UI/Widgets/Input_Widget.h
  Studio Sim/UI/Widgets/PageSlider_Widget.cpp
  Studio Sim/UI/Widgets/PageSlider_Widget.h
  Studio Sim/UI/Widgets/Widget.h
  Studio Sim/imgui.ini
Labels: engine

#113 Extra ai states
  Studio Sim/AI/AIFlee.cpp
  Studio Sim/AI/AIFollow.cpp
  Studio Sim/AI/AIFollow.h
  Studio Sim/AI/AIPatrol.cpp
  Studio Sim/AI/AIPatrol.h
  Studio Sim/AI/AIState.h
  Studio Sim/AI/AIStateMachine.cpp
  Studio Sim/AI/AIStateMachine.h
  Studio Sim/AI/AIWander.cpp
  Studio Sim/AI/AIWander.h
  Studio Sim/Components/Agent.cpp
  Studio Sim/Studio Sim.vcxproj
  Studio Sim/Studio Sim.vcxproj.filters
  Studio Sim/Utility/Helper/RND.h
  Studio Sim/imgui.ini
Labels: engine

#112 Feat/entity2 WIP
  Studio Sim/Components/Entity.cpp
  Studio Sim/Components/Entity.h
  Studio Sim/Components/EntityController.cpp
  Studio Sim/Components/EntityController.h
  Studio Sim/Components/EntityEditor.cpp
  Studio Sim/Components/EntityEditor.h
  Studio Sim/Components/Sprite.h
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Resources/Entity/Entity.json
Labels: engine

#115 Audio editor + some audio engine adaptations
  Studio Sim/Application.cpp
  Studio Sim/Audio/AudioEditor.cpp
  Studio Sim/Audio/AudioEditor.h
  Studio Sim/Audio/AudioEngine.cpp
  Studio Sim/Audio/AudioEngine.h
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Levels/Level1.h
  Studio Sim/Resources/Audio/Sound Banks/!SoundBankList.json
  Studio Sim/Resources/Audio/Sound Banks/SoundBank1.json
  Studio Sim/Resources/Audio/Sound Banks/SoundBank2.json
  Studio Sim/Resources/Audio/Sound Banks/SoundBank3.json
  Studio Sim/Resources/Audio/Sound Banks/SoundBank4.json
  Studio Sim/Resources/Audio/Sound Banks/backup copy of example sound bank.json
  Studio Sim/imgui.ini
Labels: engine

#116 Entities now have ai behaviour and collisions WIP
  Studio Sim/Components/Agent.cpp
  Studio Sim/Components/Agent.h
  Studio Sim/Components/Entity.cpp
  Studio Sim/Components/Entity.h
  Studio Sim/Components/EntityController.cpp
  Studio Sim/Components/EntityController.h
  Studio Sim/Components/EntityEditor.cpp
  Studio Sim/Components/EntityEditor.h
  Studio Sim/Levels/Level1.cpp
  Studio Sim/Resources/Entity/Entity.json
Labels: engine

#132 Entity Editor
  MH-Engine/Components/Agent.h
  MH-Engine/Components/Entity.cpp
  MH-Engine/Components/Entity.h
  MH-Engine/Components/EntityController.cpp
  MH-Engine/Components/EntityController.h
  MH-Engine/Components/EntityEditor.cpp
  MH-Engine/Components/EntityEditor.h
  MH-Engine/Components/ProjectileManager.h
  MH-Engine/Levels/Level1.cpp
  MH-Engine/Objects/Enemy.cpp
  MH-Engine/Resources/Entity/Entity.json
Labels: engine

#143 Tilemap Loader added. TM only renders when updated
  MH-Engine/Components/Entity.cpp
  MH-Engine/Components/Entity.h
  MH-Engine/Components/ProjectileManager.cpp
  MH-Engine/Components/ProjectileManager.h
  MH-Engine/Levels/Level1.cpp
  MH-Engine/Levels/Level1.h
  MH-Engine/MH-Engine.vcxproj
  MH-Engine/MH-Engine.vcxproj.filters
  MH-Engine/Resources/Entity/Entity.json
  MH-Engine/Resources/TileMaps/blue.json
  MH-Engine/TileMap/TileMapEditor.cpp
  MH-Engine/TileMap/TileMapEditor.h
  MH-Engine/TileMap/TileMapLoader.cpp
  MH-Engine/TileMap/TileMapLoader.h
Labels: engine

#148 The tileMap loading in Level is now readable and more efficient
  MH-Engine/Levels/Level1.cpp
  MH-Engine/Levels/Level1.h
  MH-Engine/TileMap/TileMapEditor.cpp
  MH-Engine/TileMap/TileMapEditor.h
  MH-Engine/TileMap/TileMapLoader.cpp
  MH-Engine/TileMap/TileMapLoader.h
Labels: engine, enhancement

#150 Feat/file handler
  MH-Engine/Components/EntityEditor.cpp
  MH-Engine/Components/ProjectileEditor.cpp
  MH-Engine/FileHandler.cpp
  MH-Engine/FileHandler.h
  MH-Engine/Levels/Level1.cpp
  MH-Engine/Levels/Level1.h
  MH-Engine/MH-Engine.vcxproj
  MH-Engine/MH-Engine.vcxproj.filters
  MH-Engine/Resources/Patterns/SlowCircle.ptn
  MH-Engine/UI/UIEditor.cpp
  MH-Engine/imgui.ini
Labels: engine, enhancement

#156 Collision Detection Filters and Events
  MH-Engine/Collisions/BoxCollider.cpp
  MH-Engine/Collisions/BoxCollider.h
  MH-Engine/Collisions/CircleCollider.cpp
  MH-Engine/Collisions/CircleCollider.h
  MH-Engine/Collisions/Collision.h
  MH-Engine/Collisions/CollisionHandler.cpp
  MH-Engine/Collisions/CollisionHandler.h
  MH-Engine/Collisions/CollisionMatrix.cpp
  MH-Engine/Collisions/CollisionMatrix.h
  MH-Engine/Collisions/LayerMask.h
  MH-Engine/Components/Collider.cpp
  MH-Engine/Components/Collider.h
  MH-Engine/Components/Entity.cpp
  MH-Engine/Components/Entity.h
  MH-Engine/MH-Engine.vcxproj
  MH-Engine/MH-Engine.vcxproj.filters
  MH-Engine/Objects/Enemy.cpp
  MH-Engine/Objects/Enemy.h
  MH-Engine/Objects/Player.cpp
  MH-Engine/Objects/Player.h
  MH-Engine/imgui.ini
Labels: engine

#159 Widget z index drawing
  MH-Engine/Resources/UI/Screens/Credits_Widgets.json
  MH-Engine/Resources/UI/Screens/HUD_Widgets.json
  MH-Engine/Resources/UI/Screens/Menu_Widgets.json
  MH-Engine/Resources/UI/Screens/Pause_Widgets.json
  MH-Engine/Resources/UI/Screens/Settings_Widgets.json
  MH-Engine/UI/UIEditor.cpp
  MH-Engine/UI/UIEditor.h
  MH-Engine/UI/UIScreen.cpp
  MH-Engine/UI/Widgets/Widget.h
Labels: engine, enhancement

#162 Added option to hide widgets
  MH-Engine/Resources/UI/Screens/Credits_Widgets.json
  MH-Engine/Resources/UI/Screens/HUD_Widgets.json
  MH-Engine/Resources/UI/Screens/Menu_Widgets.json
  MH-Engine/Resources/UI/Screens/Pause_Widgets.json
  MH-Engine/Resources/UI/Screens/Settings_Widgets.json
  MH-Engine/UI/UIEditor.cpp
  MH-Engine/UI/UIEditor.h
  MH-Engine/UI/UIScreen.cpp
  MH-Engine/UI/Widgets/Widget.h
Labels: engine, enhancement

#163 Feat/entity5 WIP
  MH-Engine/Components/Entity.cpp
  MH-Engine/Components/Entity.h
  MH-Engine/Components/EntityController.cpp
  MH-Engine/Components/EntityController.h
  MH-Engine/Components/EntityEditor.cpp
  MH-Engine/Components/ProjectileManager.cpp
  MH-Engine/Levels/Level.cpp
  MH-Engine/Resources/Entity/Entity.json
Labels: engine, enhancement

#166 Audio editor2
  MH-Engine/Audio/AudioEditor.cpp
  MH-Engine/Audio/AudioEditor.h
Labels: engine

#164 Reworked camera system
  MH-Engine/Events/Event.h
  MH-Engine/Graphics/ImGuiManager.cpp
  MH-Engine/Graphics/ImGuiManager.h
  MH-Engine/Input/Input.cpp
  MH-Engine/Levels/Level.cpp
  MH-Engine/Objects/Camera.cpp
  MH-Engine/Objects/Camera.h
  MH-Engine/imgui.ini
Labels: engine, enhancement

#171 Entity Updates
  MH-Engine/Components/Entity.cpp
  MH-Engine/Components/Entity.h
  MH-Engine/Components/EntityController.cpp
  MH-Engine/Components/EntityController.h
  MH-Engine/Levels/Level.cpp
Labels: engine, enhancement

#174 Audio random pitch and fix of random range helper function
  MH-Engine/Audio/AudioEditor.cpp
  MH-Engine/Audio/AudioEngine.cpp
  MH-Engine/Audio/AudioEngine.h
  MH-Engine/Resources/Audio/Sound Banks/SoundBank1.json
  MH-Engine/Resources/Audio/Sound Banks/SoundBank2.json
  MH-Engine/Resources/Audio/Sound Banks/SoundBank3.json
  MH-Engine/Resources/Audio/Sound Banks/SoundBank4.json
  MH-Engine/Resources/Audio/Sound Banks/backup copy of example sound bank.json
  MH-Engine/Utility/Helper/RND.h
Labels: engine, enhancement

#176 Input widget fix
  MH-Engine/Events/Event.h
  MH-Engine/Input/Input.cpp
  MH-Engine/Input/Input.h
  MH-Engine/MH-Engine.vcxproj.filters
  MH-Engine/Resources/UI/Screens/Credits_Widgets.json
  MH-Engine/UI/UIScreen.cpp
  MH-Engine/UI/UIScreen.h
  MH-Engine/UI/Widgets/Input_Widget.cpp
  MH-Engine/UI/Widgets/Input_Widget.h
Labels: bug, engine

#177 Imgui mouse interaction (detached)
  MH-Engine/AI/AIFlee.h
  MH-Engine/AI/AISeek.h
  MH-Engine/Components/Entity.h
  MH-Engine/Components/EntityEditor.cpp
  MH-Engine/Components/EntityEditor.h
  MH-Engine/Events/Event.h
  MH-Engine/Graphics/ImGuiManager.cpp
  MH-Engine/Input/Input.cpp
  MH-Engine/Input/Input.h
  MH-Engine/Levels/Level.cpp
  MH-Engine/Levels/Level.h
  MH-Engine/MH-Engine.vcxproj
  MH-Engine/MH-Engine.vcxproj.filters
  MH-Engine/Objects/Enemy.cpp
  MH-Engine/Objects/Enemy.h
  MH-Engine/Objects/Player.cpp
  MH-Engine/Objects/Player.h
  MH-Engine/UI/UIScreen.cpp
  MH-Engine/UI/Widgets/Button_Widget.cpp
  MH-Engine/UI/Widgets/DataSlider_Widget.cpp
  MH-Engine/UI/Widgets/Input_Widget.cpp
  MH-Engine/UI/Widgets/PageSlider_Widget.cpp
  MH-Engine/Utility/Helper/MouseCapture.cpp
  MH-Engine/Utility/Helper/MouseCapture.h
  MH-Engine/Window/WindowContainer.cpp
  MH-Engine/Window/WindowContainer.h
Labels: engine, enhancement

#181 Feat/animation
  MH-Engine/Components/Entity.cpp
  MH-Engine/Components/Entity.h
  MH-Engine/Components/EntityAnimation.cpp
  MH-Engine/Components/EntityAnimation.h
  MH-Engine/Components/EntityController.cpp
  MH-Engine/Components/EntityController.h
  MH-Engine/Components/EntityEditor.cpp
  MH-Engine/Components/EntityEditor.h
  MH-Engine/Components/Sprite.cpp
  MH-Engine/Components/Sprite.h
  MH-Engine/MH-Engine.vcxproj
  MH-Engine/MH-Engine.vcxproj.filters
  MH-Engine/Resources/Entity/Entity.json
  MH-Engine/Resources/Textures/Base_Projectile.json
  MH-Engine/Resources/Textures/Entity/Carrot/Carrot.json
  MH-Engine/Resources/Textures/Entity/Cauliflower/Cauliflower.json
  MH-Engine/Resources/Textures/Entity/Onion/Onion.json
  MH-Engine/Resources/Textures/Entity/Potato/Potato.json
  MH-Engine/Resources/Textures/Entity/Runner Bean/Bean.json
  MH-Engine/Resources/Textures/Entity/Runner Bean/Runner Bean.json
  MH-Engine/Resources/Textures/Entity/Tomato/Tomato.json
  MH-Engine/Utility/Helper/JsonLoading.h
Labels: engine, enhancement

#188 Collision Blacklist and Refactoring
  Roche-Engine/Collisions/BoxCollider.cpp
  Roche-Engine/Collisions/BoxCollider.h
  Roche-Engine/Collisions/CircleCollider.cpp
  Roche-Engine/Collisions/CircleCollider.h
  Roche-Engine/Collisions/CollisionHandler.cpp
  Roche-Engine/Collisions/CollisionHandler.h
  Roche-Engine/Components/Collider.cpp
  Roche-Engine/Components/Collider.h
Labels: collisions

#194 Added error checking for loading in json
  Roche-Engine/Audio/AudioEditor.cpp
  Roche-Engine/Components/ProjectileEditor.cpp
  Roche-Engine/Levels/Level.cpp
  Roche-Engine/TileMap/TileMapEditor.cpp
  Roche-Engine/Utility/Helper/JsonLoading.h
Labels: bug

#200 Feat/update map size
  Roche-Engine/Levels/Level.cpp
  Roche-Engine/Resources/Textures/Tiles/empty.png
  Roche-Engine/Resources/TileMaps/67x120file.json
  Roche-Engine/Resources/TileMaps/TileMapPaint.json
  Roche-Engine/TileMap/TileMap.h
  Roche-Engine/TileMap/TileMapEditor.cpp
  Roche-Engine/TileMap/TileMapPaintOnMap.cpp
  Roche-Engine/TileMap/TileMapPaintOnMap.h
Labels: enhancement, tile map

#202 Camera now locks to the player instead of the world
  Roche-Engine/Objects/Camera.cpp
Labels: bug
